ALTER TABLE IF EXISTS policies
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'Other',
  ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'Draft',
  ADD COLUMN IF NOT EXISTS review_frequency VARCHAR(20) DEFAULT 'Quarterly',
  ADD COLUMN IF NOT EXISTS nist_ref VARCHAR(20),
  ADD COLUMN IF NOT EXISTS is_required BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS next_review_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS created_by INTEGER,
  ADD COLUMN IF NOT EXISTS approved_by INTEGER,
  ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS rejection_note TEXT;
