export const ASSET_TYPE_OPTIONS = [
  "Information / Data Asset",
  "Hardware Asset",
  "Software Asset",
  "System / Platform",
  "Network / Communication Asset",
  "Cloud / Virtual Asset",
  "Identity / Access Asset",
  "People / Human Asset",
  "Business Process Asset",
  "Service Asset",
  "Physical / Facility Asset",
  "Documentation / Knowledge Asset",
  "Third-Party / Supplier Asset",
  "Legal / Financial / Reputation Asset",
];

export const CRITICALITY_LEVELS = [
  "Tier 0 (Life/Safety)",
  "Tier 1 (Mission Critical)",
  "Tier 2 (Business Critical)",
  "Tier 3 (Important)",
];

export const STATUS_OPTIONS = ["Active", "Inactive", "Deprecated", "Planned"];

export const DATA_CLASSIFICATION_OPTIONS = [
  "Public",
  "Internal",
  "Confidential",
  "Restricted",
];

export const ACCESS_LEVEL_OPTIONS = [
  "Internal only",
  "VPN required",
  "Public web access",
  "Public API exposed",
];

export const KEY_USERS_OPTIONS = [
  "Бүх ажилчид",
  "Зөвхөн IT хэлтэс",
  "Санхүүгийн хэлтэс",
  "Хүний нөөцийн хэлтэс",
  "Борлуулалт / Маркетингийн хэлтэс",
  "Гүйцэтгэх удирдлага",
  "Системийн администратор",
  "Харилцагч / үйлчлүүлэгч",
  "Гадаад түнш байгууллага",
  "Нийлүүлэгч / vendor",
  "Зөвхөн дотоод хэрэглэгчид",
  "Гадаад хэрэглэгчид",
  "API хэрэглэгч системүүд",
  "Бусад",
];

export const AUTHENTICATION_METHOD_OPTIONS = [
  "Username & Password",
  "Password + MFA",
  "One-Time Password (OTP)",
  "SMS OTP",
  "Email OTP",
  "Authenticator App",
  "Biometric Authentication",
  "Single Sign-On (SSO)",
  "Active Directory",
];

export const HOSTING_OPTIONS = [
  "SaaS",
  "Azure",
  "AWS",
  "GCP",
  "On-Prem",
  "Hybrid",
  "Other",
];

const HOSTING_OPTIONS_BY_ASSET_TYPE: Record<string, string[]> = {
  "Hardware Asset": ["On-Prem", "Remote", "BYOD", "Hybrid", "Other"],
  "Network / Communication Asset": [
    "On-Prem",
    "Azure",
    "AWS",
    "GCP",
    "Hybrid",
    "Other",
  ],
  "Cloud / Virtual Asset": ["Azure", "AWS", "GCP", "SaaS", "Hybrid", "Other"],
  "Third-Party / Supplier Asset": ["SaaS", "Hybrid", "Other"],
  "Endpoint Fleet": ["On-Prem", "Remote", "BYOD", "Hybrid", "Other"],
  Network: ["On-Prem", "Azure", "AWS", "GCP", "Hybrid", "Other"],
  "SaaS Tenant": ["SaaS", "Azure", "AWS", "GCP", "On-Prem", "Hybrid"],
};

export const getHostingOptions = (assetType?: string) =>
  (assetType && HOSTING_OPTIONS_BY_ASSET_TYPE[assetType]) || HOSTING_OPTIONS;

export const NATIVE_SELECT_CLASS =
  "app-form-field h-10 w-full rounded-md border px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500";

export const ASSET_TYPE_LABELS: Record<string, string> = {
  "Information / Data Asset": "Мэдээлэл / өгөгдлийн хөрөнгө",
  "Hardware Asset": "Техник хангамжийн хөрөнгө",
  "Software Asset": "Програм хангамжийн хөрөнгө",
  "System / Platform": "Систем / платформ",
  "Network / Communication Asset": "Сүлжээ ба харилцаа холбооны хөрөнгө",
  "Cloud / Virtual Asset": "Үүлэн ба виртуал хөрөнгө",
  "Identity / Access Asset": "Нэвтрэлт ба хандалтын хөрөнгө",
  "People / Human Asset": "Хүний нөөцийн хөрөнгө",
  "Business Process Asset": "Бизнес процессын хөрөнгө",
  "Service Asset": "Үйлчилгээний хөрөнгө",
  "Physical / Facility Asset": "Физик орчин ба байгууламжийн хөрөнгө",
  "Documentation / Knowledge Asset": "Баримт бичиг ба мэдлэгийн хөрөнгө",
  "Third-Party / Supplier Asset": "Гуравдагч тал / нийлүүлэгчийн хөрөнгө",
  "Legal / Financial / Reputation Asset":
    "Хууль, санхүү, нэр хүндийн хөрөнгө",
  Application: "Аппликейшн",
  Service: "Үйлчилгээ",
  Database: "Өгөгдлийн сан",
  Network: "Сүлжээ",
  "Endpoint Fleet": "Төгсгөлийн төхөөрөмж",
  Identity: "Нэвтрэлтийн систем",
  "Identity Provider": "Нэвтрэлтийн үйлчилгээ үзүүлэгч",
  "SaaS Tenant": "SaaS",
  "Business Process": "Бизнес процесс",
  "Third Party Service": "Гуравдагч талын үйлчилгээ",
  "Backup System": "Нөөцлөлтийн систем",
  Facility: "Байгууламж",
  "Data Asset": "Өгөгдлийн хөрөнгө",
  "Medical Device": "Эмнэлгийн төхөөрөмж",
  API: "API",
  Infrastructure: "Дэд бүтэц",
  "Message Queue": "Мессежийн дараалал",
  "Cache System": "Кэш систем",
  "File Storage": "Файл хадгалалт",
  "Monitoring/Logging": "Хяналт ба лог бүртгэл",
  "VPN/Remote Access": "VPN / зайнаас хандалт",
  "Load Balancer": "Ачаалал тэнцвэржүүлэгч",
  "Container Orchestration": "Контейнер зохион байгуулалт",
  "Web Server": "Вэб сервер",
  "Email System": "Имэйлийн систем",
  "Collaboration Platform": "Хамтын ажиллагааны платформ",
  Hardware: "Техник хангамж",
  Software: "Програм хангамж",
  Data: "Өгөгдөл",
  Cloud: "Үүлэн үйлчилгээ",
};

export const CRITICALITY_LABELS: Record<string, string> = {
  "Tier 0 (Life/Safety)": "Түвшин 0 (Амь нас, аюулгүй байдал)",
  "Tier 1 (Mission Critical)": "Түвшин 1 (Үндсэн үйл ажиллагаанд нэн чухал)",
  "Tier 2 (Business Critical)": "Түвшин 2 (Бизнесийн үйл ажиллагаанд чухал)",
  "Tier 3 (Important)": "Түвшин 3 (Маш Чухал)",
};

export const STATUS_LABELS: Record<string, string> = {
  Active: "Идэвхтэй",
  Inactive: "Идэвхгүй",
  Deprecated: "Хэрэглээнээс гарсан",
  Planned: "Төлөвлөгдсөн",
};

export const DATA_CLASSIFICATION_LABELS: Record<string, string> = {
  Public: "Нийтийн",
  Internal: "Дотоод",
  Confidential: "Нууц",
  Restricted: "Маш нууц",
};

export const ACCESS_LEVEL_LABELS: Record<string, string> = {
  "Internal only": "Зөвхөн дотоод сүлжээнээс",
  "VPN required": "VPN-ээр холбогдох шаардлагатай",
  "Public web access": "Интернетэд нээлттэй",
  "Public API exposed": "API нь интернэтэд нээлттэй",
};

export const AUTHENTICATION_METHOD_LABELS: Record<string, string> = {
  "Username & Password": "Хэрэглэгчийн нэр ба нууц үг",
  "Password + MFA": "Нууц үг + MFA",
  "One-Time Password (OTP)": "Нэг удаагийн нууц код (OTP)",
  "SMS OTP": "SMS OTP",
  "Email OTP": "Имэйл OTP",
  "Authenticator App": "Баталгаажуулагч апп",
  "Biometric Authentication": "Биометрик баталгаажуулалт",
  "Single Sign-On (SSO)": "Нэгдсэн нэвтрэлт (SSO)",
  "Active Directory": "Active Directory",
};

export const HOSTING_LABELS: Record<string, string> = {
  SaaS: "SaaS",
  Azure: "Azure",
  AWS: "AWS",
  GCP: "GCP",
  "On-Prem": "Дотоод байршуулалт",
  Hybrid: "Холимог",
  Remote: "Зайнаас",
  BYOD: "BYOD",
  Other: "Бусад",
};

export const RISK_LEVEL_LABELS: Record<string, string> = {
  Critical: "Ноцтой",
  High: "Өндөр",
  Medium: "Дунд",
  Low: "Бага",
};

export const ASSET_DETAIL_OPTION_LABELS: Record<string, string> = {
  "Customer data": "Харилцагчийн өгөгдөл",
  "Employee data": "Ажилтны өгөгдөл",
  "Student / patient / client records": "Оюутан / өвчтөн / үйлчлүүлэгчийн бүртгэл",
  "Financial records": "Санхүүгийн бүртгэл",
  "Contracts and legal documents": "Гэрээ ба хууль эрх зүйн баримт",
  "Business reports": "Бизнес тайлан",
  "Research documents": "Судалгааны баримт",
  "Source code": "Эх код",
  "Database records": "Өгөгдлийн сангийн бичлэг",
  "System logs": "Системийн лог",
  "Backup data": "Нөөц өгөгдөл",
  "Configuration files": "Тохиргооны файлууд",
  "Credentials / API keys / certificates / tokens":
    "Нэвтрэх мэдээлэл / API түлхүүр / сертификат / токен",
  "Desktop computer": "Суурин компьютер",
  Laptop: "Зөөврийн компьютер",
  "Mobile phone": "Гар утас",
  Tablet: "Таблет",
  Server: "Сервер",
  "Network device": "Сүлжээний төхөөрөмж",
  "Printer / scanner": "Принтер / сканнер",
  "Storage device": "Хадгалах төхөөрөмж",
  "CCTV device": "CCTV төхөөрөмж",
  "IoT device": "IoT төхөөрөмж",
  "POS terminal": "POS терминал",
  "Medical device": "Эмнэлгийн төхөөрөмж",
  "Industrial / OT device": "Үйлдвэрлэлийн / OT төхөөрөмж",
  "Operating system": "Үйлдлийн систем",
  "Web application": "Вэб аппликейшн",
  "Mobile application": "Гар утасны апп",
  "Desktop software": "Десктоп програм",
  "ERP system": "ERP систем",
  "CRM system": "CRM систем",
  "HR / payroll system": "ХН / цалингийн систем",
  "Accounting system": "Нягтлан бодох бүртгэлийн систем",
  "Database management system": "Өгөгдлийн сангийн удирдлагын систем",
  "Antivirus / EDR tool": "Антивирус / EDR хэрэгсэл",
  "SIEM / logging tool": "SIEM / логийн хэрэгсэл",
  "Backup software": "Нөөцлөлтийн програм",
  "Custom-developed system": "Дотоод хөгжүүлсэн систем",
  "Third-party SaaS application": "Гуравдагч талын SaaS апп",
  "Email system": "Имэйлийн систем",
  "Authentication system": "Нэвтрэлтийн систем",
  Website: "Вэбсайт",
  "E-commerce system": "Цахим худалдааны систем",
  "Hospital management system": "Эмнэлгийн удирдлагын систем",
  "Learning management system": "Сургалтын удирдлагын систем",
  "File sharing system": "Файл хуваалцах систем",
  "Payment system": "Төлбөрийн систем",
  "Customer support system": "Харилцагчийн үйлчилгээний систем",
  "Internal portal": "Дотоод портал",
  "Cloud platform": "Үүлэн платформ",
  "Database platform": "Өгөгдлийн сангийн платформ",
  Router: "Роутер",
  Switch: "Свич",
  Firewall: "Галт хана",
  "Wireless access point": "Утасгүй хандалтын цэг",
  VPN: "VPN",
  DNS: "DNS",
  DHCP: "DHCP",
  "Email gateway": "Имэйлийн гарц",
  "Internet connection": "Интернэт холболт",
  "VoIP / phone system": "VoIP / утасны систем",
  "Network cables": "Сүлжээний кабель",
  "Network segmentation / VLANs": "Сүлжээний сегмент / VLAN",
  "Cloud account": "Үүлэн бүртгэл",
  "Virtual machine": "Виртуал машин",
  Container: "Контейнер",
  "Kubernetes cluster": "Kubernetes кластер",
  "Cloud database": "Үүлэн өгөгдлийн сан",
  "Storage bucket": "Хадгалах bucket",
  "Serverless function": "Serverless функц",
  "Cloud IAM role": "Үүлэн IAM үүрэг",
  "Cloud security group": "Үүлэн security group",
  "Cloud backup snapshot": "Үүлэн нөөц snapshot",
  "Cloud monitoring log": "Үүлэн мониторингийн лог",
  "User account": "Хэрэглэгчийн бүртгэл",
  "Admin account": "Админ бүртгэл",
  "Privileged account": "Давуу эрхтэй бүртгэл",
  "Service account": "Сервис бүртгэл",
  "Active Directory / Entra ID": "Active Directory / Entra ID",
  "Group / role": "Бүлэг / үүрэг",
  "MFA setting": "MFA тохиргоо",
  "Password policy": "Нууц үгийн бодлого",
  "SSH key": "SSH түлхүүр",
  "API token": "API токен",
  "Digital certificate": "Дижитал сертификат",
  "Access card": "Хандалтын карт",
  Employees: "Ажилтнууд",
  "IT administrators": "IT администраторууд",
  "Security officers": "Аюулгүй байдлын ажилтнууд",
  Managers: "Менежерүүд",
  "System owners": "Системийн эзэмшигчид",
  "Business process owners": "Бизнес процессын эзэмшигчид",
  Contractors: "Гэрээт ажилтнууд",
  "Temporary workers": "Түр ажилтнууд",
  "Third-party support staff": "Гуравдагч талын дэмжлэгийн ажилтнууд",
  "Customers / users": "Харилцагчид / хэрэглэгчид",
  "Patient registration process": "Өвчтөн бүртгэх процесс",
  "Online order process": "Онлайн захиалгын процесс",
  "Payment process": "Төлбөрийн процесс",
  "Payroll process": "Цалингийн процесс",
  "Customer support process": "Харилцагчийн үйлчилгээний процесс",
  "Inventory management process": "Нөөцийн удирдлагын процесс",
  "Procurement process": "Худалдан авалтын процесс",
  "Student registration process": "Оюутан бүртгэх процесс",
  "Report generation process": "Тайлан гаргах процесс",
  "Incident response process": "Инцидентэд хариу арга хэмжээ авах процесс",
  "Backup and recovery process": "Нөөцлөлт ба сэргээх процесс",
  "Public website service": "Нийтийн вэбсайтын үйлчилгээ",
  "Public API service": "Нийтийн API үйлчилгээ",
  "Email service": "Имэйлийн үйлчилгээ",
  "Internet banking service": "Интернэт банкны үйлчилгээ",
  "Appointment booking service": "Цаг захиалгын үйлчилгээ",
  "File sharing service": "Файл хуваалцах үйлчилгээ",
  "Authentication service": "Нэвтрэлтийн үйлчилгээ",
  "Data analytics service": "Өгөгдлийн аналитикийн үйлчилгээ",
  "Backup service": "Нөөцлөлтийн үйлчилгээ",
  "Cloud hosting service": "Үүлэн байршуулалтын үйлчилгээ",
  "Office building": "Оффисын барилга",
  "Server room": "Серверийн өрөө",
  "Data center": "Дата төв",
  "Reception area": "Хүлээн авах хэсэг",
  "Storage room": "Агуулах өрөө",
  "Power supply": "Цахилгаан хангамж",
  UPS: "UPS",
  Generator: "Генератор",
  "HVAC / cooling system": "HVAC / хөргөлтийн систем",
  "Door access system": "Хаалганы хандалтын систем",
  "CCTV system": "CCTV систем",
  "Fire protection system": "Галын хамгаалалтын систем",
  "Security policy": "Аюулгүй байдлын бодлого",
  Procedure: "Журам",
  "Network diagram": "Сүлжээний зураглал",
  "System architecture diagram": "Системийн архитектурын зураглал",
  "Asset inventory": "Хөрөнгийн бүртгэл",
  "Risk register": "Эрсдэлийн бүртгэл",
  "Incident response plan": "Инцидентэд хариу арга хэмжээний төлөвлөгөө",
  "Disaster recovery plan": "Гамшгийн дараах сэргээх төлөвлөгөө",
  "Business continuity plan": "Бизнесийн тасралтгүй байдлын төлөвлөгөө",
  "User manual": "Хэрэглэгчийн гарын авлага",
  "Technical documentation": "Техникийн баримт бичиг",
  "Audit report": "Аудитын тайлан",
  "Compliance evidence": "Нийцлийн нотолгоо",
  "Cloud provider": "Үүлэн үйлчилгээ үзүүлэгч",
  "Internet provider": "Интернэтийн үйлчилгээ үзүүлэгч",
  "Software vendor": "Програм хангамжийн нийлүүлэгч",
  "Managed service provider": "Удирдлагатай үйлчилгээ үзүүлэгч",
  "Payment provider": "Төлбөрийн үйлчилгээ үзүүлэгч",
  "Outsourced IT support": "Гаднын IT дэмжлэг",
  "Security monitoring provider": "Аюулгүй байдлын мониторингийн үйлчилгээ үзүүлэгч",
  "Hardware supplier": "Техник хангамжийн нийлүүлэгч",
  "Data processing partner": "Өгөгдөл боловсруулах түнш",
  "Logistics partner": "Логистикийн түнш",
  "Organization reputation": "Байгууллагын нэр хүнд",
  "Customer trust": "Харилцагчийн итгэл",
  "Brand image": "Брэндийн имиж",
  License: "Лиценз",
  Certification: "Гэрчилгээ",
  "Compliance status": "Нийцлийн төлөв",
  "Financial resource": "Санхүүгийн нөөц",
  "Insurance contract": "Даатгалын гэрээ",
  "Intellectual property": "Оюуны өмч",
  "Trade secret": "Худалдааны нууц",
};

export const COUNTRY_REGION_MAP: Record<string, string> = {
  // Asia Pacific
  Mongolia: "Asia Pacific",
  China: "Asia Pacific",
  Japan: "Asia Pacific",
  "South Korea": "Asia Pacific",
  Australia: "Asia Pacific",
  "New Zealand": "Asia Pacific",
  India: "Asia Pacific",
  Singapore: "Asia Pacific",
  Indonesia: "Asia Pacific",
  Malaysia: "Asia Pacific",
  Thailand: "Asia Pacific",
  Vietnam: "Asia Pacific",
  Philippines: "Asia Pacific",
  Pakistan: "Asia Pacific",
  Bangladesh: "Asia Pacific",
  "Sri Lanka": "Asia Pacific",
  Nepal: "Asia Pacific",
  // US
  "United States (East)": "US-East",
  "United States (West)": "US-West",
  Canada: "US-East",
  Mexico: "US-West",
  // Europe
  "United Kingdom": "Europe",
  Germany: "Europe",
  France: "Europe",
  Netherlands: "Europe",
  Sweden: "Europe",
  Norway: "Europe",
  Denmark: "Europe",
  Finland: "Europe",
  Switzerland: "Europe",
  Austria: "Europe",
  Belgium: "Europe",
  Spain: "Europe",
  Italy: "Europe",
  Poland: "Europe",
  "Czech Republic": "Europe",
  Romania: "Europe",
  Ukraine: "Europe",
  Russia: "Europe",
  // Middle East
  "United Arab Emirates": "Middle East",
  "Saudi Arabia": "Middle East",
  Qatar: "Middle East",
  Kuwait: "Middle East",
  Bahrain: "Middle East",
  Israel: "Middle East",
  Turkey: "Middle East",
  Iran: "Middle East",
  Iraq: "Middle East",
  Jordan: "Middle East",
  // Africa
  "South Africa": "Africa",
  Nigeria: "Africa",
  Egypt: "Africa",
  Kenya: "Africa",
  Ethiopia: "Africa",
  Ghana: "Africa",
  Tanzania: "Africa",
  Morocco: "Africa",
  // South America
  Brazil: "South America",
  Argentina: "South America",
  Colombia: "South America",
  Chile: "South America",
  Peru: "South America",
  Venezuela: "South America",
};

export const COUNTRY_OPTIONS = Object.keys(COUNTRY_REGION_MAP).sort();

export const COUNTRY_LABELS: Record<string, string> = {
  Mongolia: "Монгол",
  China: "Хятад",
  Japan: "Япон",
  "South Korea": "Өмнөд Солонгос",
  Australia: "Австрали",
  "New Zealand": "Шинэ Зеланд",
  India: "Энэтхэг",
  Singapore: "Сингапур",
  Indonesia: "Индонез",
  Malaysia: "Малайз",
  Thailand: "Тайланд",
  Vietnam: "Вьетнам",
  Philippines: "Филиппин",
  Pakistan: "Пакистан",
  Bangladesh: "Бангладеш",
  "Sri Lanka": "Шри Ланк",
  Nepal: "Балба",
  "United States (East)": "АНУ (Зүүн)",
  "United States (West)": "АНУ (Баруун)",
  Canada: "Канад",
  Mexico: "Мексик",
  "United Kingdom": "Их Британи",
  Germany: "Герман",
  France: "Франц",
  Netherlands: "Нидерланд",
  Sweden: "Швед",
  Norway: "Норвеги",
  Denmark: "Дани",
  Finland: "Финланд",
  Switzerland: "Швейцар",
  Austria: "Австри",
  Belgium: "Бельги",
  Spain: "Испани",
  Italy: "Итали",
  Poland: "Польш",
  "Czech Republic": "Чех",
  Romania: "Румын",
  Ukraine: "Украин",
  Russia: "Орос",
  "United Arab Emirates": "Арабын Нэгдсэн Эмират",
  "Saudi Arabia": "Саудын Араб",
  Qatar: "Катар",
  Kuwait: "Кувейт",
  Bahrain: "Бахрейн",
  Israel: "Израил",
  Turkey: "Турк",
  Iran: "Иран",
  Iraq: "Ирак",
  Jordan: "Иордан",
  "South Africa": "Өмнөд Африк",
  Nigeria: "Нигери",
  Egypt: "Египет",
  Kenya: "Кени",
  Ethiopia: "Этиоп",
  Ghana: "Гана",
  Tanzania: "Танзани",
  Morocco: "Марокко",
  Brazil: "Бразил",
  Argentina: "Аргентин",
  Colombia: "Колумби",
  Chile: "Чили",
  Peru: "Перу",
  Venezuela: "Венесуэл",
};

export const REGION_LABELS: Record<string, string> = {
  Global: "Дэлхий даяар",
  "Asia Pacific": "Ази, Номхон далайн бүс",
  "US-East": "АНУ - Зүүн бүс",
  "US-West": "АНУ - Баруун бүс",
  Europe: "Европ",
  "Middle East": "Ойрх Дорнод",
  Africa: "Африк",
  "South America": "Өмнөд Америк",
  "On-Premises": "Дотоод байршуулалт",
};

export const getLabel = (labels: Record<string, string>, value?: string) =>
  value ? (labels[value] ?? value) : value;

export type AssetDetailField = {
  name: string;
  label: string;
  placeholder?: string;
  required?: boolean;
  input?: "text" | "textarea" | "select";
  options?: string[];
};

export type AssetTypeMetadata = {
  label: string;
  shortLabel: string;
  description: string;
  examples: string[];
  fields: AssetDetailField[];
};

export const ASSET_TYPE_METADATA: Record<string, AssetTypeMetadata> = {
  "Information / Data Asset": {
    label: "Мэдээлэл / өгөгдлийн хөрөнгө",
    shortLabel: "Өгөгдөл",
    description:
      "Байгууллага хамгаалах шаардлагатай бизнес, хувь хүн, үйл ажиллагаа, техникийн болон аюулгүй байдлын мэдээлэл.",
    examples: [
      "Харилцагчийн өгөгдөл",
      "Санхүүгийн бүртгэл",
      "Эх код",
      "Нэвтрэх мэдээлэл / API түлхүүр",
      "Нөөц өгөгдөл",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Өгөгдлийн төрөл",
        required: true,
        input: "select",
        options: [
          "Customer data",
          "Employee data",
          "Student / patient / client records",
          "Financial records",
          "Contracts and legal documents",
          "Business reports",
          "Research documents",
          "Source code",
          "Database records",
          "System logs",
          "Backup data",
          "Configuration files",
          "Credentials / API keys / certificates / tokens",
        ],
      },
      { name: "data_owner", label: "Өгөгдлийн хариуцагч", required: true },
      {
        name: "storage_location",
        label: "Хадгалах байршил / репозитор",
        required: true,
        placeholder: "Өгөгдлийн сан, файл хуваалцах сан, SaaS орчин, vault...",
      },
      {
        name: "retention_period",
        label: "Хадгалах хугацаа",
        placeholder: "7 жил, 90 хоног, байнгын...",
      },
    ],
  },
  "Hardware Asset": {
    label: "Техник хангамжийн хөрөнгө",
    shortLabel: "Техник хангамж",
    description:
      "Байгууллагын эзэмшдэг, ажиллуулдаг эсвэл ашигладаг физик технологи.",
    examples: [
      "Зөөврийн компьютер",
      "Сервер",
      "Сүлжээний төхөөрөмж",
      "Принтер",
      "IoT / CCTV төхөөрөмж",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Техник хангамжийн төрөл",
        required: true,
        input: "select",
        options: [
          "Desktop computer",
          "Laptop",
          "Mobile phone",
          "Tablet",
          "Server",
          "Network device",
          "Printer / scanner",
          "Storage device",
          "CCTV device",
          "IoT device",
          "POS terminal",
          "Medical device",
          "Industrial / OT device",
        ],
      },
      { name: "serial_number", label: "Серийн / бүртгэлийн дугаар" },
      { name: "physical_location", label: "Физик байршил", required: true },
      { name: "lifecycle_stage", label: "Амьдралын мөчлөгийн үе шат" },
    ],
  },
  "Software Asset": {
    label: "Програм хангамжийн хөрөнгө",
    shortLabel: "Програм хангамж",
    description: "Бизнесийн үйл ажиллагаанд ашиглагддаг аппликейшн, програмууд.",
    examples: [
      "Үйлдлийн систем",
      "ERP / CRM",
      "Өгөгдлийн сангийн програм",
      "EDR хэрэгсэл",
      "Дотоод хөгжүүлсэн систем",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Програм хангамжийн төрөл",
        required: true,
        input: "select",
        options: [
          "Operating system",
          "Web application",
          "Mobile application",
          "Desktop software",
          "ERP system",
          "CRM system",
          "HR / payroll system",
          "Accounting system",
          "Database management system",
          "Antivirus / EDR tool",
          "SIEM / logging tool",
          "Backup software",
          "Custom-developed system",
          "Third-party SaaS application",
        ],
      },
      { name: "vendor", label: "Нийлүүлэгч / хөгжүүлэгч", required: true },
      { name: "version", label: "Хувилбар / release" },
      { name: "license_owner", label: "Лиценз эсвэл гэрээний хариуцагч" },
    ],
  },
  "System / Platform": {
    label: "Систем / платформ",
    shortLabel: "Систем / платформ",
    description:
      "Техник хангамж, програм хангамж, өгөгдөл, хэрэглэгч, процессыг нэгтгэсэн систем.",
    examples: [
      "Имэйлийн систем",
      "Нэвтрэлтийн систем",
      "Вэбсайт",
      "Төлбөрийн систем",
      "Үүлэн платформ",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Систем / платформын төрөл",
        required: true,
        input: "select",
        options: [
          "Email system",
          "Authentication system",
          "Website",
          "E-commerce system",
          "Hospital management system",
          "Learning management system",
          "File sharing system",
          "Payment system",
          "Customer support system",
          "Internal portal",
          "Cloud platform",
          "Database platform",
        ],
      },
      { name: "system_owner", label: "Системийн хариуцагч", required: true },
      {
        name: "primary_components",
        label: "Үндсэн бүрэлдэхүүн",
        input: "textarea",
        placeholder: "Апп, өгөгдлийн сан, хэрэглэгч, интеграц...",
      },
      { name: "supported_process", label: "Дэмждэг бизнес процесс" },
    ],
  },
  "Network / Communication Asset": {
    label: "Сүлжээ ба харилцаа холбооны хөрөнгө",
    shortLabel: "Сүлжээ",
    description: "Холболт, урсгалын хяналт, харилцаа холбоог дэмждэг хөрөнгө.",
    examples: ["Роутер", "Свич", "Галт хана", "VPN", "DNS / DHCP"],
    fields: [
      {
        name: "asset_subtype",
        label: "Сүлжээ / харилцаа холбооны төрөл",
        required: true,
        input: "select",
        options: [
          "Router",
          "Switch",
          "Firewall",
          "Wireless access point",
          "VPN",
          "DNS",
          "DHCP",
          "Email gateway",
          "Internet connection",
          "VoIP / phone system",
          "Network cables",
          "Network segmentation / VLANs",
        ],
      },
      { name: "network_zone", label: "Сүлжээний бүс / сегмент", required: true },
      { name: "ip_range", label: "IP хүрээ / hostname" },
      { name: "connectivity_dependency", label: "Холболтын хамаарал" },
    ],
  },
  "Cloud / Virtual Asset": {
    label: "Үүлэн ба виртуал хөрөнгө",
    shortLabel: "Үүлэн",
    description: "Үүлэн бүртгэл, виртуал дэд бүтэц, cloud-native нөөцүүд.",
    examples: [
      "Үүлэн бүртгэл",
      "Виртуал машин",
      "Контейнер",
      "Kubernetes кластер",
      "Хадгалах bucket",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Үүлэн / виртуал төрөл",
        required: true,
        input: "select",
        options: [
          "Cloud account",
          "Virtual machine",
          "Container",
          "Kubernetes cluster",
          "Cloud database",
          "Storage bucket",
          "Serverless function",
          "Cloud IAM role",
          "Cloud security group",
          "Cloud backup snapshot",
          "Cloud monitoring log",
        ],
      },
      { name: "cloud_provider", label: "Үүлэн үйлчилгээ үзүүлэгч", required: true },
      { name: "account_project", label: "Бүртгэл / төсөл / subscription" },
      { name: "resource_identifier", label: "Нөөцийн танигч" },
    ],
  },
  "Identity / Access Asset": {
    label: "Нэвтрэлт ба хандалтын хөрөнгө",
    shortLabel: "Нэвтрэлт",
    description:
      "Бүртгэл, үүрэг, бодлого, түлхүүр болон танин баталгаажуулалтын хяналтууд.",
    examples: [
      "Админ бүртгэл",
      "Сервис бүртгэл",
      "Entra ID",
      "MFA тохиргоо",
      "API токен",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Нэвтрэлт / хандалтын төрөл",
        required: true,
        input: "select",
        options: [
          "User account",
          "Admin account",
          "Privileged account",
          "Service account",
          "Active Directory / Entra ID",
          "Group / role",
          "MFA setting",
          "Password policy",
          "SSH key",
          "API token",
          "Digital certificate",
          "Access card",
        ],
      },
      { name: "identity_provider", label: "Нэвтрэлтийн үйлчилгээ үзүүлэгч", required: true },
      { name: "privilege_level", label: "Эрхийн түвшин", required: true },
      { name: "access_scope", label: "Хандалтын хамрах хүрээ" },
    ],
  },
  "People / Human Asset": {
    label: "Хүний нөөцийн хөрөнгө",
    shortLabel: "Хүмүүс ба үүрэг",
    description:
      "Систем ажиллуулдаг, шийдвэр гаргадаг эсвэл аюулгүй байдалд нөлөөлдөг хүмүүс.",
    examples: [
      "Ажилтнууд",
      "IT администраторууд",
      "Аюулгүй байдлын ажилтнууд",
      "Гэрээт ажилтнууд",
      "Гуравдагч талын дэмжлэгийн ажилтнууд",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Хүний нөөцийн төрөл",
        required: true,
        input: "select",
        options: [
          "Employees",
          "IT administrators",
          "Security officers",
          "Managers",
          "System owners",
          "Business process owners",
          "Contractors",
          "Temporary workers",
          "Third-party support staff",
          "Customers / users",
        ],
      },
      { name: "role_group", label: "Үүрэг / бүлэг", required: true },
      { name: "employment_type", label: "Ажил эрхлэлт / оролцооны төрөл" },
      {
        name: "security_responsibilities",
        label: "Аюулгүй байдлын хариуцлага",
        input: "textarea",
      },
    ],
  },
  "Business Process Asset": {
    label: "Бизнес процессын хөрөнгө",
    shortLabel: "Бизнес процесс",
    description:
      "Тасалдвал бизнесийн нөлөөлөл үүсгэдэг үйл ажиллагааны урсгалууд.",
    examples: [
      "Өвчтөн бүртгэл",
      "Төлбөрийн процесс",
      "Цалингийн процесс",
      "Худалдан авалт",
      "Нөөцлөлт ба сэргээх",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Бизнес процессын төрөл",
        required: true,
        input: "select",
        options: [
          "Patient registration process",
          "Online order process",
          "Payment process",
          "Payroll process",
          "Customer support process",
          "Inventory management process",
          "Procurement process",
          "Student registration process",
          "Report generation process",
          "Incident response process",
          "Backup and recovery process",
        ],
      },
      { name: "process_owner", label: "Процессын хариуцагч", required: true },
      { name: "process_frequency", label: "Давтамж / хуваарь" },
      {
        name: "dependencies",
        label: "Шаардлагатай систем, өгөгдөл, хүмүүс, нийлүүлэгчид",
        input: "textarea",
      },
    ],
  },
  "Service Asset": {
    label: "Үйлчилгээний хөрөнгө",
    shortLabel: "Үйлчилгээ",
    description:
      "Байгууллага үзүүлдэг эсвэл үйл ажиллагаандаа түшиглэдэг үйлчилгээ.",
    examples: [
      "Нийтийн вэб үйлчилгээ",
      "Имэйлийн үйлчилгээ",
      "Нэвтрэлтийн үйлчилгээ",
      "Нөөцлөлтийн үйлчилгээ",
      "Үүлэн байршуулалтын үйлчилгээ",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Үйлчилгээний төрөл",
        required: true,
        input: "select",
        options: [
          "Public website service",
          "Public API service",
          "Email service",
          "Internet banking service",
          "Appointment booking service",
          "File sharing service",
          "Authentication service",
          "Data analytics service",
          "Backup service",
          "Cloud hosting service",
        ],
      },
      { name: "service_owner", label: "Үйлчилгээний хариуцагч", required: true },
      { name: "service_consumers", label: "Хэрэглэгчид" },
      { name: "sla", label: "SLA / хүртээмжийн зорилт" },
    ],
  },
  "Physical / Facility Asset": {
    label: "Физик орчин ба байгууламжийн хөрөнгө",
    shortLabel: "Байгууламж",
    description:
      "Үйл ажиллагааг хамгаалдаг физик байршил болон дэмжих дэд бүтэц.",
    examples: [
      "Оффисын барилга",
      "Серверийн өрөө",
      "UPS",
      "HVAC",
      "Хаалганы хандалтын систем",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Байгууламжийн төрөл",
        required: true,
        input: "select",
        options: [
          "Office building",
          "Server room",
          "Data center",
          "Reception area",
          "Storage room",
          "Power supply",
          "UPS",
          "Generator",
          "HVAC / cooling system",
          "Door access system",
          "CCTV system",
          "Fire protection system",
        ],
      },
      { name: "facility_location", label: "Байршил", required: true },
      { name: "facility_owner", label: "Байгууламжийн хариуцагч" },
      {
        name: "physical_security_controls",
        label: "Физик аюулгүй байдлын хяналтууд",
        input: "textarea",
      },
    ],
  },
  "Documentation / Knowledge Asset": {
    label: "Баримт бичиг ба мэдлэгийн хөрөнгө",
    shortLabel: "Баримт бичиг",
    description:
      "Аюулгүй ажиллахад шаардлагатай бодлого, зураглал, төлөвлөгөө, нотолгоо, мэдлэг.",
    examples: [
      "Аюулгүй байдлын бодлого",
      "Сүлжээний зураглал",
      "Эрсдэлийн бүртгэл",
      "Инцидентэд хариу арга хэмжээний төлөвлөгөө",
      "Аудитын тайлан",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Баримт бичгийн төрөл",
        required: true,
        input: "select",
        options: [
          "Security policy",
          "Procedure",
          "Network diagram",
          "System architecture diagram",
          "Asset inventory",
          "Risk register",
          "Incident response plan",
          "Disaster recovery plan",
          "Business continuity plan",
          "User manual",
          "Technical documentation",
          "Audit report",
          "Compliance evidence",
        ],
      },
      { name: "document_owner", label: "Баримтын хариуцагч", required: true },
      { name: "repository", label: "Репозитор / байршил", required: true },
      { name: "review_cycle", label: "Хянах давтамж" },
    ],
  },
  "Third-Party / Supplier Asset": {
    label: "Гуравдагч тал / нийлүүлэгчийн хөрөнгө",
    shortLabel: "Гуравдагч тал",
    description:
      "Байгууллагад эрсдэл үүсгэж болзошгүй гаднын талууд болон хамаарлууд.",
    examples: [
      "Үүлэн үйлчилгээ үзүүлэгч",
      "Интернэтийн үйлчилгээ үзүүлэгч",
      "Програмын нийлүүлэгч",
      "Удирдлагатай үйлчилгээ үзүүлэгч",
      "Төлбөрийн үйлчилгээ үзүүлэгч",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Нийлүүлэгчийн төрөл",
        required: true,
        input: "select",
        options: [
          "Cloud provider",
          "Internet provider",
          "Software vendor",
          "Managed service provider",
          "Payment provider",
          "Outsourced IT support",
          "Security monitoring provider",
          "Hardware supplier",
          "Data processing partner",
          "Logistics partner",
        ],
      },
      { name: "supplier_name", label: "Нийлүүлэгч / түншийн нэр", required: true },
      { name: "contract_owner", label: "Гэрээний хариуцагч", required: true },
      { name: "service_scope", label: "Үйлчилгээний хамрах хүрээ", input: "textarea" },
      { name: "data_access", label: "Өгөгдөл / системийн хандалт" },
    ],
  },
  "Legal / Financial / Reputation Asset": {
    label: "Хууль, санхүү, нэр хүндийн хөрөнгө",
    shortLabel: "Хууль ба нэр хүнд",
    description:
      "Кибер инцидент, нийцлийн алдаа, итгэл алдалтаас хохирч болзошгүй биет бус хөрөнгө.",
    examples: [
      "Байгууллагын нэр хүнд",
      "Брэндийн имиж",
      "Лиценз",
      "Нийцлийн төлөв",
      "Худалдааны нууц",
    ],
    fields: [
      {
        name: "asset_subtype",
        label: "Биет бус хөрөнгийн төрөл",
        required: true,
        input: "select",
        options: [
          "Organization reputation",
          "Customer trust",
          "Brand image",
          "License",
          "Certification",
          "Compliance status",
          "Financial resource",
          "Insurance contract",
          "Intellectual property",
          "Trade secret",
        ],
      },
      { name: "asset_owner", label: "Хөрөнгийн хариуцагч", required: true },
      { name: "impact_area", label: "Үндсэн нөлөөллийн талбар", required: true },
      { name: "protection_goal", label: "Хамгаалах зорилго", input: "textarea" },
    ],
  },
};
